apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-providers-db-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
