apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-providers-config
  labels:
    app: ms-providers
data:
  PORT: '3333'
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DRIVE_DISK: 'local'
  RABBITMQ_HOSTNAME: 'event-bus'
  RABBITMQ_PORT: '5672'
  RABIITMQ_PROTOCOL: 'ampq://'
